export interface Recommendation {
  id: string;
  name: string;
  title: string;
  relationship: string;
  date: string;
  text: string;
  linkedinUrl?: string;
}

export const recommendations: Recommendation[] = [
  {
    id: "jialin-liu",
    name: "Jialin Liu",
    title: "PhD Student in Information, University of Wisconsin-Madison",
    relationship: "Jialin was Tanay's mentor",
    date: "April 27, 2026",
    text: `I had the opportunity to collaborate with Tanay on a research project. There's a version of research assistance where someone executes tasks competently and that's enough. Tanay did that, but the more interesting thing was watching him get genuinely curious about why things worked.

We were forecasting which biomedical research clusters face elevated retraction risk, the kind of problem with no clean literature to follow. Tanay didn't just run models; he wanted to understand what the features were actually measuring. Why would authorship turnover predict future retractions? What does the geographic composition of an author team capture that a citation count doesn't? These questions made the SHAP analysis more than a feature-importance table. It became something we could reason about.

The "out-of-time validation" piece is worth mentioning too. He'd read enough on forecasting methodology to know that temporal leakage is how models lie, and he built the evaluation framework accordingly. His insistence caught the methodological gap early.`,
  },
  {
    id: "ian-hutchins",
    name: "Ian Hutchins",
    title: "Assistant Professor of Data and Information Science at the University of Wisconsin-Madison Information School",
    relationship: "Ian managed Tanay directly",
    date: "April 22, 2026",
    text: `I've had the pleasure of working with Tanay on a research project to forecast the biomedical research subfields that are at elevated risk for future retractions. This is a technically demanding project at the intersection of network science, machine learning, and science policy.

Tanay developed our machine learning pipeline that works with topics generated by an unsupervised graph clustering algorithm to predict which fields will have elevated retraction rates in the future. This involved feature selection, hyperparameter tuning, model selection, and out-of-time validation. This kind of time-series discipline (preventing data from the future from leaking into the past) is often overlooked in research articles, but crucial for forecasting. Tanay's modeling has yielded a number of models that predict a field's future retraction rate with an R-squared in excess of 0.5, which is excellent for a prediction model of this type.

Tanay will be a great asset to any team working on machine learning, data science, or computational social science. He works well in a team, takes initiative, and can operationalize high-level goals into complex tasks very effectively. I highly recommend Tanay to anyone he chooses to engage with in the future.`,
  },
];
